- hosts: servers
  become: yes
  tasks:
    - name: Install Docker
      apt:
        name: docker-ce
        state: present
        update_cache: yes  # به روزرسانی کش برای نصب

    - name: Ensure Docker service is running
      service:
        name: docker
        state: started
        enabled: yes

    - name: Create directory for application files
      file:
        path: /root/deploy/my-app-flask/
        state: directory
        owner: your_user
        group: your_group
        mode: '0755'
    
    - name: Copy application files to the target server
      synchronize:
        src: /home/gitlab-runner/builds/iLX2yTsKH/0/root/my-app-flask/
        dest: /root/deploy/my-app-flask/
        mode: push
        recursive: yes
        rsync_opts:
          - "--exclude=*.pyc"  # مثال برای جلوگیری از انتقال فایل‌های pyc
          
    - name: Pull Docker image
      docker_image:
        name: my-flask-app
        tag: "{{ CI_COMMIT_TAG }}"
        source: pull

    - name: Stop and remove old Docker container if exists
      docker_container:
        name: my-flask-app
        state: absent  # حذف کانتینر قدیمی اگر وجود داشته باشد
        ignore_errors: yes

    - name: Run Docker container
      docker_container:
        name: my-flask-app
        image: my-flask-app:{{ CI_COMMIT_TAG }}
        state: started
        ports:
          - "8081:8081"
