- hosts: servers
  become: yes
  tasks:
    - name: Clean APT cache
      apt:
        clean: yes
      ignore_errors: yes

    - name: Update APT cache
      apt:
        update_cache: yes

    - name: Install resolvconf
      apt:
        name: resolvconf
        state: present

    - name: Configure permanent DNS servers
      blockinfile:
        path: /etc/resolvconf/resolv.conf.d/head
        create: yes
        block: |
          nameserver 10.202.10.202
          nameserver 10.202.10.102
          nameserver 178.22.122.100
          nameserver 185.51.200.2
        marker: "# {mark} ANSIBLE MANAGED BLOCK"

    - name: Update resolvconf
      command: resolvconf -u

    - name: Disable systemd-resolved
      systemd:
        name: systemd-resolved
        state: stopped
        enabled: no

    - name: Install prerequisites
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu noble stable
        state: present

    - name: Update APT cache again
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Ensure Docker service is running
      service:
        name: docker
        state: started
        enabled: yes

    - name: Create directory for application files
      file:
        path: /root/deploy/my-app-flask/
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Copy application files to the target server
      synchronize:
        src: /home/gitlab-runner/builds/iLX2yTsKH/0/root/my-app-flask/
        dest: /root/deploy/my-app-flask/
        mode: push
        recursive: yes
        rsync_opts:
          - "--exclude=*.pyc"

    - block:
        - name: Stop and remove old Docker container if exists
          docker_container:
            name: my-flask-app
            state: absent

      rescue:
        - name: Handle error if container does not exist
          debug:
            msg: "Container 'my-flask-app' does not exist, continuing with the next steps."

    - name: Build Docker image
      shell: |
        cd /root/deploy/my-app-flask/
        docker build -t my-flask-app:{{ CI_COMMIT_TAG }} .

    - name: Run Docker container
      docker_container:
        name: my-flask-app
        image: my-flask-app:{{ CI_COMMIT_TAG }}
        state: started
        ports:
          - "8081:8081"
